Sofie-Automation/sofie-package-manager

- shared/packages/worker/src/worker/accessorHandlers/httpProxy.ts
- shared/packages/worker/src/worker/accessorHandlers/lib/fetch.ts
This PR introduces a `refreshStream` option to the `fetchWithController` options argument. It is of the type `NodeJS.ReadableStream | undefined`.
When a `refreshStream` is provided, `fetchWithController` will monitor the `data` event of the `refreshStream` and use that to refresh the fetch timeout. This ensures that active file uploads (such as preview generation of long media packages) won't get prematurely aborted by said timeout.
> fix: prevent active httpProxy file uploads from timing out

- shared/packages/worker/src/worker/workers/windowsWorker/expectationHandlers/lib/scan.ts
- shared/packages/worker/src/worker/workers/windowsWorker/expectationHandlers/packageDeepScan.ts
Currently, the deep scan process fails on audio-only files and throws an error. This PR prevents those errors from occurring.
In this PR, deep scanning audio-only files is effectively a no-op, but in the future there may be information we want to extract from audio files during this step.
> fix: allow deep scanning of audio-only files

- apps/package-manager/packages/generic/src/expectationGenerator.ts
- shared/packages/api/src/expectationApi.ts
- shared/packages/worker/src/worker/workers/windowsWorker/expectationHandlers/fileCopy.ts
- shared/packages/worker/src/worker/workers/windowsWorker/expectationHandlers/fileVerify.ts
- shared/packages/worker/src/worker/workers/windowsWorker/lib/lib.ts
- shared/packages/worker/src/worker/workers/windowsWorker/windowsWorker.ts
This PR Adds the expectationHandler "fileVerify", used to just verify that a file exists,
This is useful when copying a file into a folder is handled manually, and we just want to verify that the file exists in that folder.
> Feat: verify file

- README.md
This PR adds links to the Sofie System Documentation, specifically the Quick Start docs for Package Manager.
> docs(README): add link to quick start instructions

- apps/appcontainer-node/packages/generic/src/appContainer.ts
- shared/packages/worker/src/worker/accessorHandlers/atem.ts
- shared/packages/worker/src/worker/accessorHandlers/fileShare.ts
- shared/packages/worker/src/worker/lib/lib.ts
- shared/packages/worker/src/worker/workers/windowsWorker/expectationHandlers/lib/ffmpeg.ts
- shared/packages/worker/src/worker/workers/windowsWorker/expectationHandlers/lib/scan.ts
- shared/packages/worker/src/worker/workers/windowsWorker/lib/robocopy.ts
This PR replaces some situations where `execFile` is used instead of `spawn`, and the remaining uses of `execFile` are expanded with a sufficiently large buffer.
> fix: worker child processes exit with null code

- apps/http-server/packages/generic/src/server.ts
The HTTP server should accept both keys for HEAD requests as well
> fix: accept apiKeyRead and apiKeyWrite for HEAD requests as well

- apps/package-manager/packages/generic/src/generateExpectations/nrk/expectations.ts
- apps/package-manager/packages/generic/src/generateExpectations/nrk/lib.ts
- apps/package-manager/packages/generic/src/generateExpectations/nrk/packageContainerExpectations.ts
- apps/package-manager/packages/generic/src/generateExpectations/nrk/smartbull.ts
- apps/package-manager/packages/generic/src/packageManager.ts
- shared/packages/api/src/packageContainerApi.ts
- shared/packages/expectationManager/src/expectationManager.ts
- shared/packages/expectationManager/src/lib/constants.ts
- shared/packages/worker/src/worker/accessorHandlers/fileShare.ts
- shared/packages/worker/src/worker/accessorHandlers/http.ts
- shared/packages/worker/src/worker/accessorHandlers/httpProxy.ts
- shared/packages/worker/src/worker/accessorHandlers/lib/FileHandler.ts
- shared/packages/worker/src/worker/accessorHandlers/localFolder.ts
This PR adds a feature to the Package Container cleanup-cronjob, the `cleanFileAge`. When set, any file older than a certain time will be removed from the PackageContainer.
This is useful for certain types of PackageContainers where we want to clean up old files after ourselves, like for a temporary storage.
> Feat: clean temporary storage

- shared/packages/worker/src/worker/workers/windowsWorker/expectationHandlers/lib/scan.ts
We have feedback that the default 2s black frame detection threshold is impractical. Proposing a more practical, 200ms.
> fix: use a shorter time-span for black frame detection

- shared/packages/worker/src/worker/workers/windowsWorker/expectationHandlers/lib/scan.ts
This PR fixes an issue where the blackDetectRegex doesn't properly match if the black_duration is an integer without a decimal part.
> fix: blackDetectRegex expects black_duration to be a number with a decimal point

- .github/workflows/build-windows.yaml
- package.json
builds are produced for each push to `master` or `release**` branch, and made available as an artifact on the workflow run. This workflow can also be triggered manually for any other branch.  
any tags pushed will also be built, and will have the produced binaries published as a release
example run producing a release:
https://github.com/Julusian/sofie-package-manager/actions/runs/3911835824/jobs/6685687396
https://github.com/Julusian/sofie-package-manager/releases/tag/v0.0.1
note: as this is a fork, it is skipping the signing step.
signing is shown to be working:
https://github.com/nrkno/sofie-package-manager/actions/runs/3910714913/jobs/6683239584
> chore: build windows binaries in ci

- shared/packages/expectationManager/src/expectationManager.ts
fix: when an exp is waiting for another exp, it will be jumping between WAITING and NEW unnecessarily.
This changes the behaviour so that it stays in WAITING state.
> fix: exp jump NEW -> WAITING -> NEW when waiting for another exp

- shared/packages/api/src/__tests__/lib.spec.ts
- shared/packages/api/src/lib.ts
- shared/packages/expectationManager/src/expectationManager.ts
An update to expectation.priority only should only result in a minor update.
This should possibly fix the issue, or at least make if more visible why it's resulting in a major update.
> Fix: expectation should "minor"-update when changing priority only

- apps/package-manager/packages/generic/src/configManifest.ts
- apps/package-manager/packages/generic/src/coreHandler.ts
- shared/packages/api/src/lib.ts
Add a default value for "Delay removal of packages" to be used by Package Manager when no value is being manually configured.
> feat: default package and package info removal delay

- apps/package-manager/packages/generic/src/packageManager.ts
- apps/single-app/app/src/singleApp.ts
- shared/packages/api/src/config.ts
- shared/packages/api/src/lib.ts
- shared/packages/expectationManager/src/expectationManager.ts
- shared/packages/worker/src/worker/accessorHandlers/lib/CachedQuantelGateway.ts
- shared/packages/worker/src/worker/accessorHandlers/quantel.ts
- tests/internal-tests/package.json
- tests/internal-tests/src/__mocks__/tv-automation-quantel-gateway-client.ts
- tests/internal-tests/src/__tests__/basic.spec.ts
- tests/internal-tests/src/__tests__/issues.spec.ts
- tests/internal-tests/src/__tests__/lib/lib.ts
- tests/internal-tests/src/__tests__/quantel.spec.ts
This PR fixes a few issues:
* don't set `concurrency` as a CLI default value. Instead allow it to be undefined so that the default value (in constants.ts) takes effect.
* Improve unit tests to make them more robust.
* update quantel-gateway-client mock
* rework CachedQuantelGateway, fixing a few issues:
* Add a `purgeCache()` - call from quantel after a copy has finished, so that the copied clip is always reflected to later calls to `searchClip()`
* Remove a few seldom-used methods from cache (`connectToISA`, `getClip`, `getZones`, `getServers`)
* change the scheduling of purging expired items from cache, so that it is triggered (using setTimeout) by an activity rather than on an interval. This is done because there currently wasn't any way to clear the setInterval.
Most of these things …
> Fix: Failing unit tests

- shared/packages/api/src/worker.ts
- shared/packages/expectationManager/src/evaluationRunner/evaluateExpectationStates/waiting.ts
- shared/packages/worker/src/worker/accessorHandlers/atem.ts
- shared/packages/worker/src/worker/accessorHandlers/corePackageInfo.ts
- shared/packages/worker/src/worker/accessorHandlers/fileShare.ts
- shared/packages/worker/src/worker/accessorHandlers/genericHandle.ts
- shared/packages/worker/src/worker/accessorHandlers/http.ts
- shared/packages/worker/src/worker/accessorHandlers/httpProxy.ts
- shared/packages/worker/src/worker/accessorHandlers/lib/lib.ts
- shared/packages/worker/src/worker/accessorHandlers/localFolder.ts
- shared/packages/worker/src/worker/accessorHandlers/quantel.ts
- shared/packages/worker/src/worker/workers/windowsWorker/expectationHandlers/jsonDataCopy.ts
- shared/packages/worker/src/worker/workers/windowsWorker/expectationHandlers/lib/file.ts
- shared/packages/worker/src/worker/workers/windowsWorker/expectationHandlers/mediaFilePreview.ts
- shared/packages/worker/src/worker/workers/windowsWorker/expectationHandlers/mediaFileThumbnail.ts
- shared/packages/worker/src/worker/workers/windowsWorker/expectationHandlers/packageDeepScan.ts
- shared/packages/worker/src/worker/workers/windowsWorker/expectationHandlers/packageScan.ts
- shared/packages/worker/src/worker/workers/windowsWorker/expectationHandlers/quantelClipCopy.ts
- shared/packages/worker/src/worker/workers/windowsWorker/expectationHandlers/quantelClipPreview.ts
- shared/packages/worker/src/worker/workers/windowsWorker/expectationHandlers/quantelClipThumbnail.ts
- shared/packages/worker/src/worker/workers/windowsWorker/lib/lib.ts
- tests/internal-tests/src/__mocks__/tv-automation-quantel-gateway-client.ts
- tests/internal-tests/src/__tests__/quantel.spec.ts
This PR includes some refactoring, but mainly it adds the `packageExists` property to the result of `tryPackageRead()` method, in order to return better sourceExists from `isFileReadyToStartWorkingOn()`.
In practice, this causes "reserved quantel clips" to get the status NOT_READY instead of NOT_FOUND, which is slightly more accurate.
> Fix: sourceExists

- shared/packages/worker/src/worker/accessorHandlers/lib/__tests__/pathJoin.spec.ts
- shared/packages/worker/src/worker/accessorHandlers/lib/pathJoin.ts
This PR fixes a bug and adds unit tests for the `joinUrls` function.
The bug appeared when trying to join the paths `joinUrls("asdf/package", "//nas/folder/path")`
> fix: bug in joinUrls

- apps/http-server/packages/generic/src/storage/fileStorage.ts
- shared/packages/api/src/lib.ts
- shared/packages/worker/src/worker/accessorHandlers/http.ts
- shared/packages/worker/src/worker/accessorHandlers/httpProxy.ts
- shared/packages/worker/src/worker/accessorHandlers/lib/fetch.ts
This PR is being opened on behalf of TV 2 Norway.
TV 2 Norway has some files with `#` characters in them. Because of the semantic meaning of `#` in URLs (specifically: the fact that anything after a `#` is never sent to the server in an HTTP request), we have to ensure that we treat filenames with this character in it appropriately.
I've tested this with a few different filenames, both containing `#` and not, but this should definitely get tested against a more comprehensive NRK suite before being merged.
> fix: handle # in filenames and urls (%23, when URI encoded)

- apps/package-manager/packages/generic/src/generateExpectations/nrk/expectations-lib.ts
- shared/packages/api/src/expectationApi.ts
- shared/packages/expectationManager/src/evaluationRunner/evaluateExpectationStates/fulfilled.ts
- tests/internal-tests/src/__mocks__/fs.ts
- tests/internal-tests/src/__tests__/issues.spec.ts
This PR fixes a bug where thumbnails & previews lingered as fullfilled for packages that are long gone in Sofie.
**New behaviour:**
1. Expectations that depend on others are un-fulfilled whenever any of the depended-upon expectations are not fullfilled.
2. Thumbnails and Previews (files) are removed when an expectation moves away from being `fulfilled` (using the new property `removePackageOnUnFulfill`).
> fix: Thumbnails & Previews linger for packages that are long gone (SOFIE-2293)

- apps/package-manager/packages/generic/src/coreHandler.ts
- apps/package-manager/packages/generic/src/generateExpectations/nrk/expectations.ts
- package.json
- yarn.lock
Updated server-core-integration to be using correct typings following https://github.com/nrkno/sofie-core/pull/906
There is also a fix for a type error reported by typescript in vscode (it defaulted to typescript 5.1, rather than the 4.9 in the project).
It was reporting ` Operator '>' cannot be applied to types 'Any' and 'number' `, which looks like an accurate error based on the property definition `accessors: { [accessorId: string]: AccessorOnPackage.Any }`
The line below was to make the tests pass, so I'm not 100% sure of it
> chore: update server-core-integration

- apps/http-server/app/src/index.ts
- apps/http-server/app/tsconfig.json
- apps/http-server/packages/generic/src/server.ts
- apps/http-server/packages/generic/src/storage/fileStorage.ts
- apps/http-server/packages/generic/tsconfig.json
- apps/single-app/app/src/index.ts
- apps/single-app/app/tsconfig.json
This is an experiment to see if the problem with the cut-off files is caused by resolving the save promise too early.
> experiment: see if the problem is resolving the postPackage promise too early

- shared/packages/worker/src/worker/workers/windowsWorker/expectationHandlers/lib.ts
- shared/packages/worker/src/worker/workers/windowsWorker/expectationHandlers/mediaFilePreview.ts
- shared/packages/worker/src/worker/workers/windowsWorker/expectationHandlers/mediaFileThumbnail.ts
This PR is being opened on behalf of TV 2 Norge.
This PR generates audio waveform images as thumbnails for audio-only files.
The waveform images currently look like this, with the channels being separated:
FFMPEG documentation on how to generate different-looking waveforms can be found here: https://trac.ffmpeg.org/wiki/Waveform
This has been implemented on the Sofie side as well: https://github.com/nrkno/sofie-core/pull/981
> feat: generate audio waveform images for audio-only files

- shared/packages/worker/src/worker/workers/windowsWorker/expectationHandlers/mediaFilePreview.ts
This PR is being opened on behalf of TV 2 Norge.
The current behavior is that if a preview generation expectation for an audio-only file comes in, PM will throw errors due to the lack of video streams.
This PR simply skips preview generation if no video streams are found.
> fix: don't error when trying to generate a preview for an audio-only file

- shared/packages/worker/src/worker/workers/windowsWorker/lib/robocopy.ts
This is a: 
Bug fix
The `cleanup` cronjob should clean up files that are older than 30 days.
But if a source file is old it gets cleaned up prematurely, because robocopy copies the timestamps by default.
robocopy does not copy the timestamp.
Draft, because not tested yet
> fix: robocopy should not copy timstamps (SOFIE-2986)

- apps/package-manager/packages/generic/src/$schemas/options.json
- apps/package-manager/packages/generic/src/coreHandler.ts
- apps/package-manager/packages/generic/src/generateExpectations/nrk/__tests__/nrk.spec.ts
- apps/package-manager/packages/generic/src/generateExpectations/nrk/expectations.ts
- apps/package-manager/packages/generic/src/generated/options.ts
- apps/package-manager/packages/generic/src/packageManager.ts
This is useful as a performance improvement in some installations where we don't use/want the deep scanning info anyway
This is a: Minor feature 
In one installation, NRK has a special build of PM that has deep scanning disabled, for improved performance.
This PR adds an option to the config manifest, to allow for skipping of deep scanning in the Sofie settings GUI.
* Enable the setting, test that deep scanning is skipped
> fix: Add option to skip deep scanning of expectations (SOFIE-3060)

- shared/packages/expectationManager/src/expectationTracker/lib/trackedExpectationAPI.ts
- shared/packages/expectationManager/src/internalManager/lib/trackedWorkerAgents.ts
This pull request is posted on behalf of the NRK
This is a:  Bug fix
When workers closed down, their ids where left in the trackedExp.availableWorkers, so the only old, invalid workers where queried, and not the new ones. This caused PM to try to spin up new workers indefinitely.
Closed down workers are cleaned up from availableWorkers & queriedWorkers.
Also, if availableWorkers is empty, the expectation is moved to the NEW state, so that a new query for available workers is done.
> Fix: closed workers are note cleaned up in availableWorkers & queriedWorkers  (SOFIE-3073)

- shared/packages/worker/src/worker/accessorHandlers/lib/CachedQuantelGateway.ts
… time
This is a: Bug fix 
We observed a situation where there where MANY calls to `connect/` at the Quantel Gateway from Package Manager, resulting in overwhelming the quantel gateway and subsequent timeouts.
While I haven't pinpointed the exact root cause of this, this might help in ensuring that we only send one call at a time.
Only one call to `connect/` at the Quantel Gateway is sent at a time.
> chore: fix: ensure the cache is cleared on error (SOFIE-3061)

- apps/package-manager/packages/generic/src/generateExpectations/nrk/expectations-lib.ts
- apps/package-manager/packages/generic/src/generateExpectations/nrk/expectations.ts
- apps/package-manager/packages/generic/src/generateExpectations/nrk/types.ts
- apps/single-app/app/expectedPackages.json
- shared/packages/api/src/expectationApi.ts
- shared/packages/api/src/inputApi.ts
- shared/packages/worker/package.json
- shared/packages/worker/src/worker/workers/genericWorker/expectationHandlers/lib/coreApi.ts
- shared/packages/worker/src/worker/workers/genericWorker/expectationHandlers/lib/scan.ts
- shared/packages/worker/src/worker/workers/genericWorker/expectationHandlers/packageIframesScan.ts
- shared/packages/worker/src/worker/workers/genericWorker/genericWorker.ts
- yarn.lock
This pull request is posted on behalf of TV 2 Norge.
This is a: 
Feature
There is no way to tell whether a video package is intra-frame compressed or where the I-frames are.
By specifying `iframes: true` in `sideEffects`, I-frames scan can be enabled for video packages. The scan result provides information about the compression: whether it's intra-frame, fixed I-frame distance (and what the distance is), or if it's variable-distance (and where the I-frames are).
This can be useful when working with video players that can't seek to any arbitrary frame, only to I-frames.
It can be tested using the single-app in local-only mode, using packages from expectedPackages.json. At least three sample files are needed: intra-frame, with constant I-frame distance, and with variable I-frame distance …
> feat: add I-frames scan side-effect

- shared/packages/worker/src/worker/accessorHandlers/http.ts
- shared/packages/worker/src/worker/accessorHandlers/httpProxy.ts
This pull request is posted on behalf of the NRK
This is a: Bug fix
PM doesn't handle bad response codes properly, so we _can_ happen to store a bad response in the jsonDataCopy job.
bad (>=400) error responses are handled better.
> fix: handle bad http respnse codes better (SOFIE-3616)

- apps/appcontainer-node/packages/generic/src/appContainer.ts
- scripts/prepare-for-tests.mjs
- shared/packages/api/src/worker.ts
- shared/packages/expectationManager/src/evaluationRunner/evaluateExpectationStates/fulfilled.ts
- shared/packages/expectationManager/src/evaluationRunner/evaluateExpectationStates/waiting.ts
- shared/packages/expectationManager/src/expectationTracker/lib/trackedExpectationAPI.ts
- shared/packages/worker/src/worker/accessorHandlers/quantel.ts
This is a: Bug fix
We saw a situation in production that PM was not handling very well.
**Issue A:**
There was an expectation that throw in workOnExpectation with error:
```
"Error: Clip id 123456789 not found"
```
And PM reported the errors as bad status, which didn't look too good.
**Issue B:**
Expectations that are fulfilled but are waiting for another expectation get stuck in a state loop `fullfilled->new->waiting->fullfilled`.
PM will handle the issues more gracefully.
**Issue A:** Expectations will stay in WAITING state when the Quantel clip is not found, without throwing errors.
**Issue B:** Those expectations will not loop through the states anymore.
> fix: state machine improvements and error handling (SOFIE-3751)

- shared/packages/worker/src/dummyAppContainerApi.ts
- shared/packages/worker/src/workerAgent.ts
- tests/internal-tests/src/__tests__/lib/setupEnv.ts
This is a: 
Feature
It is possible to run the worker process without an appContainerURL specified, in which case it will operate in standalone mode. This is the new default, when running the worker process independently. The workers will have `appContainerURL` provided when started by the App Container (so called "single-app" mode).
* Run the worker process independently and see if it doesn't shut down automatically
* Run the single-process package manager and see if it operates as before.
> feat(worker): when appContainerURL is not specified, run standalone, for external management
